version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn surefire-report:report
      - mvn package
      - echo Build completed on `date`      
reports:
  SurefireReports:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'
artifacts:
  files:
    - target/JavaApp.war
